generator:
  strategy:
    config:
      table-prefix: t_
      include: t_member,t_member_car
  global:
    config:
      author: zhuxuchao
      module-prefix: video-
      multi-module: true
      open: false
  package:
    config:
      parent: com.zhuxc.video.ringtone
  datasource:
    config:
      url: jdbc:mysql://49.232.12.83:3306/xiche?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: wechat_mysql_83
      driver-name: com.mysql.cj.jdbc.Driver
