generator:
  strategy:
    config:
      table-prefix: t_sys_,t_bus_
      include:
      super-entity-class: com.maoface.share.common.Entity
  global:
    config:
      author: zhuxuchao
#      module-prefix: video-
      multi-module: false
      open: false
      fileOverride: true
      swagger2: true
      base-result-map: true
      base-column-list: true
  package:
    config:
      parent: com.maoface.share
  datasource:
    config:
      url: jdbc:mysql://rm-m5e66r6o610j9l8noko.mysql.rds.aliyuncs.com:3306/share?useSSL=true
      username: share
      password: '!Q2w#E4r%T'
      driver-name: com.mysql.cj.jdbc.Driver


